### PR TITLE
direct JPG saving

### PR DESCRIPTION
**Pull request by jywarren**
re #36

### CODE REVIEW

**Comment by jywarren** [comment]
Hmm. What am I doing wrong here? 

```
    2) should send response
  2 passing (2m)
  2 failing
  1) /GET /ap1/v2/export
       should send response:
     Error: Timeout of 100000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/app/test/process.js)
  ```

https://travis-ci.org/github/publiclab/image-sequencer-app/builds/673562138#L1288

**Comment by tech4GT** [comment]
@jywarren This looks good to me! 😃 
I think the tests are failing not because of the content of this PR. I'll modify the tests and maybe you can pull the changes in on this?

**Comment by tech4GT** [comment]
I see! Since we changed the API the tests can't really test this version anymore! Let me temporarily comment out our tests until we can figure out an efficient way of testing this out!

**Comment by tech4GT** [comment]
Okay done! I think we can merge this in directly!

**Review by tech4GT — APPROVED** [review]

**Comment by jywarren** [comment]
OK, i'll rebase this!

**Comment by jywarren** [comment]
Awesome!!!

**Pull request merged**
