### PR TITLE
Distortion fix WIP

### PR DESCRIPTION
**Pull request by jywarren**
(based on @tech4gt's dev)

### CODE REVIEW

**Comment by tech4GT** [comment]
Okay @jywarren I tried this out and the result I am getting is this:
incorrect
Can you post a screenshot of what you got?

**Comment by tech4GT** [comment]
Or is this an corner ordering issue on my part!

**Comment by jywarren** [comment]
Yes, it needs a unique corner ordering AND a `*-1` as per this comment: https://github.com/publiclab/image-sequencer-app/issues/23#issuecomment-522172802

**Comment by jywarren** [comment]
So this is outputting:

```
[ { x: 7, y: 186 },
  { x: 163, y: 0 },
  { x: 153, y: 163 },
  { x: 0, y: 89 } ]
```

But as per the screenshot in #23, we need:

```
[  { x: 0, y: 89 },
  { x: 163, y: 0 },
  { x: 153, y: 163 },
 { x: 7, y: 186 }]
```

and, we need to multiply the `y` values by -1

**Comment by jywarren** [comment]
OK, I did it here. Can we merge and republish?

**Comment by jywarren** [comment]
Then the google storage part should be our next task!

**Comment by tech4GT** [comment]
Oh, I see a couple of issues on the server side. Do you mind if I fix them first?

**Comment by jywarren** [comment]
for sure!

**Comment by tech4GT** [comment]
Awesome @jywarren !! :heart: 
This is really nice!! Thanks a ton for helping with this!!

**Comment by tech4GT** [comment]
Okay a small issue in the if conditions, I'll push that change just now.
One more thing is with the overlay and final canvas size(which was our original issue :sweat_smile: ).
So my idea is to make the final canvas size dependent on the scale too and for the final positions of where to overlay, let me cook up a strategy for that! Our earlier strategy won't really work, so we somehow have to hook up the image overlay locations to the final canvas size!

**Comment by tech4GT** [comment]
Oh I just realized I can't push to your branch! Let's merge this and then go from there?

**Comment by tech4GT** [comment]
@jywarren Can you open the pr to the dev branch rather than main? I don't want incomplete code being deployed automatically.

**Comment by jywarren** [comment]
OK, did it! And cloud upload seems to be working! 🎉 

Do you think you can get it to produce, instead of the HTML file, the same format `status.json` as https://github.com/publiclab/mapknitter-exporter-sinatra - and to use that format to point to the JPG output?

**Comment by tech4GT** [comment]
Sure! I'll look into it!
But let's go to that after figuring our our overlay situation! That's literally the only thing left yay!

**Comment by jywarren** [comment]
Yes!!!

**Comment by tech4GT** [comment]
@jywarren I think I have identified the issue with overlay! The thing is that warping the image with some particular coordinates does not change its size, for instance if we warp with the maximum x being 180, that does not mean the final image width will be 180.
In essence after warping we need to resize the images so that they match the coordinate system we are using!

**Comment by tech4GT** [comment]
For instance if we are warping with these values
```
[  { x: 0, y: 89 },
  { x: 163, y: 0 },
  { x: 153, y: 163 },
 { x: 7, y: 186 }]
```
We should resize our Image to be 163x186

**Comment by tech4GT** [comment]
What do you think @jywarren ??

**Comment by jywarren** [comment]
Ah, interesting. Yes, i guess that makes sense! Can we track this in a new issue? Are you saying we've solved the distortion issue but not the placement during compositing? Thanks!

**Comment by tech4GT** [comment]
Yeah I think that's just the thing, our overlay calculations are actually using the scaled coordinates but since we never resized the image according to it.
The existing resize module can't really handle this uae case so I suppose I'll write and publish a custom one one on npm.

**Comment by tech4GT** [comment]
I think we already have an issue for this, I'll update that with this!

**Pull request closed without merging**
